version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: postgres-juris
    restart: always
    environment:
      POSTGRES_DB: jurisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: